# -*- coding: utf-8 -*-
"""DBMS_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxrOJeLJl4Y7mB81dr2y1Dp7WPrRq1pQ
"""

import pandas as pd

# Load the CSV file
file_path = "/content/2024 DATA.csv"
play_calls_df = pd.read_csv(file_path)

# Define standardization function
def standardize(val):
    if pd.isna(val) or val == "":
        return None
    return " ".join(val.strip().title().split())

# Standardize all columns used for matching in both dataframes
cols_to_standardize = ['PlayType', 'Formation', 'PassType', 'RushDirection']
for col in cols_to_standardize:
    play_calls_df[col] = play_calls_df[col].apply(standardize)

# Create the plays_df (keep this as it is)
plays_data = [
    (101, 'PASS', 'Shotgun', 'Short Left', None),
    (102, 'PASS', 'Shotgun', 'Short Middle', None),
    (103, 'PASS', 'Shotgun', 'Short Right', None),
    (104, 'PASS', 'Shotgun', 'Deep Left', None),
    (105, 'PASS', 'Shotgun', 'Deep Middle', None),
    (106, 'PASS', 'Shotgun', 'Deep Right', None),
    (107, 'PASS', 'Under Center', 'Short Left', None),
    (108, 'PASS', 'Under Center', 'Short Middle', None),
    (109, 'PASS', 'Under Center', 'Short Right', None),
    (110, 'PASS', 'Under Center', 'Deep Left', None),
    (111, 'PASS', 'Under Center', 'Deep Middle', None),
    (112, 'PASS', 'Under Center', 'Deep Right', None),
    (113, 'PASS', 'No Huddle', 'Short Left', None),
    (114, 'PASS', 'No Huddle', 'Short Middle', None),
    (115, 'PASS', 'No Huddle', 'Short Right', None),
    (116, 'PASS', 'No Huddle', 'Deep Left', None),
    (117, 'PASS', 'No Huddle', 'Deep Middle', None),
    (118, 'PASS', 'No Huddle', 'Deep Right', None),
    (119, 'PASS', 'No Huddle Shotgun', 'Short Left', None),
    (120, 'PASS', 'No Huddle Shotgun', 'Short Middle', None),
    (121, 'PASS', 'No Huddle Shotgun', 'Short Right', None),
    (122, 'PASS', 'No Huddle Shotgun', 'Deep Left', None),
    (123, 'PASS', 'No Huddle Shotgun', 'Deep Middle', None),
    (124, 'PASS', 'No Huddle Shotgun', 'Deep Right', None),
    (125, 'RUSH', 'Shotgun', None, 'Centre'),
    (126, 'RUSH', 'Shotgun', None, 'Left Guard'),
    (127, 'RUSH', 'Shotgun', None, 'Right Guard'),
    (128, 'RUSH', 'Shotgun', None, 'Left Tackle'),
    (129, 'RUSH', 'Shotgun', None, 'Right Tackle'),
    (130, 'RUSH', 'Shotgun', None, 'Left End'),
    (131, 'RUSH', 'Shotgun', None, 'Right End'),
    (132, 'RUSH', 'Under Center', None, 'Centre'),
    (133, 'RUSH', 'Under Center', None, 'Left Guard'),
    (134, 'RUSH', 'Under Center', None, 'Right Guard'),
    (135, 'RUSH', 'Under Center', None, 'Left Tackle'),
    (136, 'RUSH', 'Under Center', None, 'Right Tackle'),
    (137, 'RUSH', 'Under Center', None, 'Left End'),
    (138, 'RUSH', 'Under Center', None, 'Right End'),
    (139, 'RUSH', 'No Huddle', None, 'Centre'),
    (140, 'RUSH', 'No Huddle', None, 'Left Guard'),
    (141, 'RUSH', 'No Huddle', None, 'Right Guard'),
    (142, 'RUSH', 'No Huddle', None, 'Left Tackle'),
    (143, 'RUSH', 'No Huddle', None, 'Right Tackle'),
    (144, 'RUSH', 'No Huddle', None, 'Left End'),
    (145, 'RUSH', 'No Huddle', None, 'Right End'),
    (146, 'RUSH', 'No Huddle Shotgun', None, 'Centre'),
    (147, 'RUSH', 'No Huddle Shotgun', None, 'Left Guard'),
    (148, 'RUSH', 'No Huddle Shotgun', None, 'Right Guard'),
    (149, 'RUSH', 'No Huddle Shotgun', None, 'Left Tackle'),
    (150, 'RUSH', 'No Huddle Shotgun', None, 'Right Tackle'),
    (151, 'RUSH', 'No Huddle Shotgun', None, 'Left End'),
    (152, 'RUSH', 'No Huddle Shotgun', None, 'Right End'),
    (153, 'FIELD GOAL', 'Field Goal', None, None),
    (154, 'PUNT', 'Punt', None, None),
    (155, 'PUNT', 'Under Center', None, None),
    (156, 'SCRAMBLE', 'Shotgun', None, None),
    (157, 'SCRAMBLE', 'Under Center', None, None),
    (158, 'SCRAMBLE', 'No Huddle', None, None),
    (159, 'SCRAMBLE', 'No Huddle Shotgun', None, None),
    (160, 'SACK', 'Shotgun', None, None),
    (161, 'SACK', 'Under Center', None, None),
    (162, 'SACK', 'No Huddle', None, None),
    (163, 'SACK', 'No Huddle Shotgun', None, None),
    (164, 'PENALTY', 'Under Center', None, None),
    (165, 'PENALTY', 'No Huddle Shotgun', None, None),
    (166, 'TIMEOUT', 'Under Center', None, None),
    (167, 'EXTRA POINT', 'Under Center', None, None),
    (168, 'TWO-POINT CONVERSION', 'Under Center', None, None),
    (169, 'QB Kneel', 'Under Center', None, None),
    (170, 'QB Kneel', 'No Huddle', None, None),
    (171, 'QB Kneel', 'Shotgun', None, None),
    (172, 'CLOCK STOP', 'No Huddle', None, None),
    (173, 'EXCEPTION', 'Under Center', None, None),
    (174, 'EXCEPTION', 'Shotgun', None, None),
    (175, 'FUMBLES', 'Under Center', None, None),
    (176, 'FUMBLES', 'Shotgun', None, None),
    (177, 'FUMBLES', 'No Huddle Shotgun', None, None),
    (178, 'FUMBLES', 'No Huddle', None, None),
    (179, 'NO PLAY', 'Under Center', None, None),
    (180, 'NO PLAY', 'Shotgun', None, None),
    (181, 'NO PLAY', 'No Huddle Shotgun', None, None),
    (182, 'NO PLAY', 'No Huddle', None, None),
    (183, 'KICK OFF', 'Under Center', None, None)
]
plays_df = pd.DataFrame(plays_data, columns=["Play_ID", "Type", "Formation", "PassType", "RushDirection"])

# Standardize values in plays_df
for col in ['Type', 'Formation', 'PassType', 'RushDirection']:
    plays_df[col] = plays_df[col].apply(standardize)

# Merge based on standardized values
merged_df = pd.merge(
    play_calls_df,
    plays_df,
    how='left',
    left_on=['PlayType', 'Formation', 'PassType', 'RushDirection'],
    right_on=['Type', 'Formation', 'PassType', 'RushDirection']
)

# Drop helper column and show only successful matches
merged_df = merged_df.drop(columns=['Type'])
matched_df = merged_df[merged_df['Play_ID'].notna()]
matched_df['Play_ID'] = matched_df['Play_ID'].astype(int)

# Display rows with successful Play_ID matches
print(matched_df[['PlayType', 'Formation', 'PassType', 'RushDirection', 'Play_ID']])

matched_df.to_csv('PlayCalls_With_Numeric_PlayID.csv', index=False)